# Generated by Django 4.2.3 on 2023-07-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='내용')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='posts_photo', verbose_name='이미지')),
            ],
        ),
    ]
